name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        feature: [default, evm, starknet, all]

    steps:
    - uses: actions/checkout@v4
    - name: Build (${{ matrix.feature }})
      run: |
        case "${{ matrix.feature }}" in
          default) cargo build --verbose ;;
          all) cargo build --verbose --all-features ;;
          *) cargo build --verbose --features "${{ matrix.feature }}" ;;
        esac
    - name: Run tests (${{ matrix.feature }})
      run: |
        case "${{ matrix.feature }}" in
          default) cargo test --verbose ;;
          all) cargo test --verbose --all-features ;;
          *) cargo test --verbose --features "${{ matrix.feature }}" ;;
        esac
